
# NOTE: this example targets the master branch of i3status-rust.
#
# For latest stable version, refer to
# https://github.com/greshake/i3status-rust/blob/v0.22.0/examples/config.toml

icons_format = "{icon}"

[theme]
theme = "dracula"
[theme.overrides]

[icons]
icons = "awesome"
[icons.overrides]
bat = ""
# battery logo and 100% charge
bat_full = " |   100% | "
bat_charging = "  |^| "
bat_discharging = "   |v| "

[[block]]
block = "cpu"
interval = 5


[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(2) "
format_alt = " $icon_swap $swap_used_percents.eng(2) "
interval = 30

# battery 
[[block]]
block = "battery"
interval = 60
device = "BAT0"

[[block]]
block = "temperature"
interval = 30

[[block]]
block = "uptime"
interval = 300

[[block]]
block = "xrandr"
interval = 1000

[[block]]
block = "custom"
command = "sed 's/  //' <(curl 'https://wttr.in/?format=1' -s)"
interval = 3600

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 600
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(2) "

# music 
[[block]]
block = "music"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

# wifi 
[[block]]
block = "custom"
command = "nmcli -t -f GENERAL.STATE device show wlp3s0 | awk '{print $2}' | sed 's/connected//;s/disconnected/睊/'"
interval = 10
[[block.click]]
button = "left"
cmd = "plasma-open-settings"

[[block]]
block = "time"
interval = 10
format = " %a %d/%m %R:%S "

[[block]]
block = "custom"
# verify update with check update command
command = "echo \" $(checkupdates | wc -l)\""
interval = 7200


[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
interval = "once"
[[block.click]]
button = "left"
cmd = "systemctl `echo -e 'suspend\npoweroff\nreboot' | dmenu`"
